version: "3.8"
name: db-stack
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <host_port> : <container_port>
      - "3306:3306"
    volumes:
      - "./db_scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db_scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
  jpa-db:
    image: mysql:5.7
    restart: always
    container_name: jpa-db
    environment:
      MYSQL_DATABASE: "jpa-db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <host_port> : <container_port>
      - "3307:3306"
