CREATE TABLE IF NOT EXISTS STUDENTS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    FACULTY_NUMBER VARCHAR(20) UNIQUE,
    DELETED TIMESTAMP NULL,
    CREATED TIMESTAMP DEFAULT NOW()
);